### ISSUE TITLE
Better "dot" notation sugar for mutating properties

### ISSUE THREAD

**Issue by tjb1982** [tjb1982/flax#1]
Currently in an environment document, you can mutate maps such as

``` yaml
foo:
  bar:
    baz: lala
  quux:
  - first
  - second
  - third: true
```

like this:

``` yaml
foo.bar.baz: something which is not "lala"
foo.quux.2.third: false
```

Which is great, but in order to append to collections, it gets awkward:

``` yaml
foo.bar:
  ~(assoc:
  - ~@foo.bar
  - ~:extra
  - blah

foo.quux:
  ~(conj:
  - ~@foo.quux
  - fourth
```

It would be nice if there were a shortcut, like this:

``` yaml
foo.bar.:
  extra: blah
foo.quux.: fourth
```

or even:

``` yaml
foo.:
  bar.:
    extra: blah
  quux.: fourth
```
