### ISSUE TITLE
Throwable needs to be differentiated from testable

### ISSUE THREAD

**Issue by tjb1982** [tjb1982/flax#1]
Right now there's a single key called `throw` which is used to indicate whether a test should be counted among the failures at the end of the test. There needs to be a way to actually throw the test (i.e., not continue, clean-up, etc.) upon some condition. In conjunction with that there needs to be a separate key that indicates whether the process should be considered a failure or ignored. And I think this key will need to be a function that takes `out` `err` `exit` as parameters. 

```yaml
# means that flax should stop and cleanup if the checkpoint fails
throw: boolean
assert:
    ~(fn:
    - [ out, err, exit ]
    - ~(zero?: [ exit ]
```

If `throw` is `true` and no `assert` key is set, it should just check the exit code for non-zero, otherwise it should throw based on the pass/fail of the assertion.
