### ISSUE TITLE
Support for multidoc yaml

### ISSUE THREAD

**Issue by tjb1982** [tjb1982/flax#2]
co.nclk/clj-yaml (a fork from circleci/clj-yaml) now supports multidoc strings, like:

``` yaml
pets:
  june:
    type: dog
  chester:
    type: dog

---

pets.foo: bar
pets.chester.type: chunkus

```

But flax currently doesn't take advantage of them. The benefit would be that the previous document's entries would be mutable by the second document.
